[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "certifi>=2020.06.20",
    "oldest-supported-numpy",
    "pybind11>=2.6",
    "setuptools_scm>=7",
]

[tool.isort]
known_mpltoolkits = "mpl_toolkits"
known_pydata = "numpy, matplotlib.pyplot"
known_firstparty = "matplotlib"
sections = "FUTURE,STDLIB,THIRDPARTY,PYDATA,FIRSTPARTY,MPLTOOLKITS,LOCALFOLDER"
no_lines_before = "MPLTOOLKITS"
force_sort_within_sections = true

[tool.ruff]
exclude = [
    ".git",
    "build",
    "doc/gallery",
    "doc/tutorials",
    "tools/gh_api.py",
    ".tox",
    ".eggs",
]
ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D200",
    "D202",
    "D204",
    "D205",
    "D301",
    "D400",
    "D401",
    "D403",
    "D404",
    "E741",
    "F841",
]
line-length = 88
select = [
    "D",
    "E",
    "F",
    "W",
]

# The following error codes are not supported by ruff v0.0.240
# They are planned and should be selected once implemented
# even if they are deselected by default.
# These are primarily whitespace/corrected by autoformatters (which we don't use).
# See https://github.com/charliermarsh/ruff/issues/2402 for status on implementation
external = [
  "E122",
  "E201",
  "E202",
  "E203",
  "E221",
  "E251",
  "E261",
  "E272",
  "E302",
  "E703",
]

target-version = "py39"

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.ruff.per-file-ignores]
"setup.py" = ["E402"]

"doc/conf.py" = ["E402"]
"galleries/examples/animation/frame_grabbing_sgskip.py" = ["E402"]
"galleries/examples/lines_bars_and_markers/marker_reference.py" = ["E402"]
"galleries/examples/misc/print_stdout_sgskip.py" = ["E402"]
"galleries/examples/style_sheets/bmh.py" = ["E501"]
"galleries/examples/subplots_axes_and_figures/demo_constrained_layout.py" = ["E402"]
"galleries/examples/text_labels_and_annotations/custom_legends.py" = ["E402"]
"galleries/examples/ticks/date_concise_formatter.py" = ["E402"]
"galleries/examples/ticks/date_formatters_locators.py" = ["F401"]
"galleries/examples/user_interfaces/embedding_in_gtk3_panzoom_sgskip.py" = ["E402"]
"galleries/examples/user_interfaces/embedding_in_gtk3_sgskip.py" = ["E402"]
"galleries/examples/user_interfaces/embedding_in_gtk4_panzoom_sgskip.py" = ["E402"]
"galleries/examples/user_interfaces/embedding_in_gtk4_sgskip.py" = ["E402"]
"galleries/examples/user_interfaces/gtk3_spreadsheet_sgskip.py" = ["E402"]
"galleries/examples/user_interfaces/gtk4_spreadsheet_sgskip.py" = ["E402"]
"galleries/examples/user_interfaces/mpl_with_glade3_sgskip.py" = ["E402"]
"galleries/examples/user_interfaces/pylab_with_gtk3_sgskip.py" = ["E402"]
"galleries/examples/user_interfaces/pylab_with_gtk4_sgskip.py" = ["E402"]
"galleries/examples/userdemo/pgf_preamble_sgskip.py" = ["E402"]

"lib/matplotlib/__init__.py" = ["E402", "F401"]
"lib/matplotlib/_animation_data.py" = ["E501"]
"lib/matplotlib/_api/__init__.py" = ["F401"]
"lib/matplotlib/axes/__init__.py" = ["F401", "F403"]
"lib/matplotlib/backends/backend_template.py" = ["F401"]
"lib/matplotlib/font_manager.py" = ["E501"]
"lib/matplotlib/image.py" = ["F401", "F403"]
"lib/matplotlib/pylab.py" = ["F401", "F403"]
"lib/matplotlib/pyplot.py" = ["F401", "F811"]
"lib/matplotlib/tests/test_mathtext.py" = ["E501"]
"lib/mpl_toolkits/axisartist/__init__.py" = ["F401"]
"lib/pylab.py" = ["F401", "F403"]

"galleries/tutorials/advanced/path_tutorial.py" = ["E402"]
"galleries/tutorials/advanced/patheffects_guide.py" = ["E402"]
"galleries/tutorials/advanced/transforms_tutorial.py" = ["E402", "E501"]
"galleries/tutorials/colors/colormaps.py" = ["E501"]
"galleries/tutorials/colors/colors.py" = ["E402"]
"galleries/tutorials/intermediate/artists.py" = ["E402"]
"galleries/tutorials/intermediate/constrainedlayout_guide.py" = ["E402"]
"galleries/tutorials/intermediate/legend_guide.py" = ["E402"]
"galleries/tutorials/intermediate/tight_layout_guide.py" = ["E402"]
"galleries/tutorials/introductory/animation_tutorial.py" = ["E501"]
"galleries/tutorials/introductory/images.py" = ["E501"]
"galleries/tutorials/introductory/pyplot.py" = ["E402", "E501"]
"galleries/tutorials/text/annotations.py" = ["E402", "E501"]
"galleries/tutorials/text/mathtext.py" = ["E501"]
"galleries/tutorials/text/text_intro.py" = ["E402"]
"galleries/tutorials/text/text_props.py" = ["E501"]
